package com.carhub.model;

// Generated Sep 22, 2015 9:30:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.faces.bean.ManagedBean;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ItemData generated by hbm2java
 */
@Entity
@Table(name = "item_data", catalog = "carhub")
@ManagedBean(name="itemData")
public class ItemData implements java.io.Serializable {

	private Long itemId;
	private String itemName;
	private Set particulars = new HashSet(0);

	public ItemData() {
	}

	public ItemData(String itemName, Set particulars) {
		this.itemName = itemName;
		this.particulars = particulars;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "item_id", unique = true, nullable = false)
	public Long getItemId() {
		return this.itemId;
	}

	public void setItemId(Long itemId) {
		this.itemId = itemId;
	}

	@Column(name = "item_name", length = 100)
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "itemData")
	public Set<Particular> getParticulars() {
		return this.particulars;
	}

	public void setParticulars(Set particulars) {
		this.particulars = particulars;
	}

}
