package com.carhub.model;

// Generated Sep 22, 2015 9:30:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.faces.bean.ManagedBean;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Job generated by hbm2java
 */
@Entity
@Table(name = "job", catalog = "carhub")
@ManagedBean(name="job")
public class Job implements java.io.Serializable {

	private Long jobId;
	private Customer customer;
	private JobType jobType;
	private Vehicle vehicle;
	private Date jobDate;
	private Set particulars = new HashSet(0);

	public Job() {
	}

	public Job(Customer customer, JobType jobType) {
		this.customer = customer;
		this.jobType = jobType;
	}

	public Job(Customer customer, JobType jobType, Vehicle vehicle,
			Date jobDate, Set particulars) {
		this.customer = customer;
		this.jobType = jobType;
		this.vehicle = vehicle;
		this.jobDate = jobDate;
		this.particulars = particulars;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "job_id", unique = true, nullable = false)
	public Long getJobId() {
		return this.jobId;
	}

	public void setJobId(Long jobId) {
		this.jobId = jobId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "job_type_id", nullable = false)
	public JobType getJobType() {
		return this.jobType;
	}

	public void setJobType(JobType jobType) {
		this.jobType = jobType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vehicle_id")
	public Vehicle getVehicle() {
		return this.vehicle;
	}

	public void setVehicle(Vehicle vehicle) {
		this.vehicle = vehicle;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "job_date", length = 19)
	public Date getJobDate() {
		return this.jobDate;
	}

	public void setJobDate(Date jobDate) {
		this.jobDate = jobDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "job")
	public Set<Particular> getParticulars() {
		return this.particulars;
	}

	public void setParticulars(Set particulars) {
		this.particulars = particulars;
	}

}
