package com.carhub.model;

// Generated Sep 22, 2015 9:30:19 PM by Hibernate Tools 3.4.0.CR1

import javax.faces.bean.ManagedBean;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Particular generated by hbm2java
 */
@Entity
@Table(name = "particular", catalog = "carhub")
@ManagedBean(name="particular")
public class Particular implements java.io.Serializable {

	private Long particularId;
	private ItemData itemData;
	private Job job;
	private Double partPrice;
	private Double labourPrice;
	private Double totalPrice;

	public Particular() {
	}

	public Particular(ItemData itemData, Job job, Double partPrice,
			Double labourPrice, Double totalPrice) {
		this.itemData = itemData;
		this.job = job;
		this.partPrice = partPrice;
		this.labourPrice = labourPrice;
		this.totalPrice = totalPrice;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "particular_id", unique = true, nullable = false)
	public Long getParticularId() {
		return this.particularId;
	}

	public void setParticularId(Long particularId) {
		this.particularId = particularId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "item_id")
	public ItemData getItemData() {
		return this.itemData;
	}

	public void setItemData(ItemData itemData) {
		this.itemData = itemData;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "job_id")
	public Job getJob() {
		return this.job;
	}

	public void setJob(Job job) {
		this.job = job;
	}

	@Column(name = "part_price", precision = 22, scale = 0)
	public Double getPartPrice() {
		return this.partPrice;
	}

	public void setPartPrice(Double partPrice) {
		this.partPrice = partPrice;
	}

	@Column(name = "labour_price", precision = 22, scale = 0)
	public Double getLabourPrice() {
		return this.labourPrice;
	}

	public void setLabourPrice(Double labourPrice) {
		this.labourPrice = labourPrice;
	}

	@Column(name = "total_price", precision = 22, scale = 0)
	public Double getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(Double totalPrice) {
		this.totalPrice = totalPrice;
	}

}
