package com.carhub.model;

// Generated Sep 22, 2015 9:30:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.faces.bean.ManagedBean;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vehicle generated by hbm2java
 */
@Entity
@Table(name = "vehicle", catalog = "carhub")
@ManagedBean(name="vehicle")
public class Vehicle implements java.io.Serializable {

	private Long vehicleId;
	private Customer customer;
	private String vehicleNumber;
	private String model;
	private Date soldDate;
	private Double kilometre;
	private Set jobs = new HashSet(0);

	public Vehicle() {
	}

	public Vehicle(Customer customer, String vehicleNumber, String model,
			Date soldDate, Double kilometre, Set jobs) {
		this.customer = customer;
		this.vehicleNumber = vehicleNumber;
		this.model = model;
		this.soldDate = soldDate;
		this.kilometre = kilometre;
		this.jobs = jobs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "vehicle_id", unique = true, nullable = false)
	public Long getVehicleId() {
		return this.vehicleId;
	}

	public void setVehicleId(Long vehicleId) {
		this.vehicleId = vehicleId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "customer_id")
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@Column(name = "vehicle_number", length = 50)
	public String getVehicleNumber() {
		return this.vehicleNumber;
	}

	public void setVehicleNumber(String vehicleNumber) {
		this.vehicleNumber = vehicleNumber;
	}

	@Column(name = "model", length = 100)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "sold_date", length = 19)
	public Date getSoldDate() {
		return this.soldDate;
	}

	public void setSoldDate(Date soldDate) {
		this.soldDate = soldDate;
	}

	@Column(name = "kilometre", precision = 22, scale = 0)
	public Double getKilometre() {
		return this.kilometre;
	}

	public void setKilometre(Double kilometre) {
		this.kilometre = kilometre;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "vehicle")
	public Set<Job> getJobs() {
		return this.jobs;
	}

	public void setJobs(Set jobs) {
		this.jobs = jobs;
	}

}
